apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume1
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kvol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim1
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi