kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
 
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: nitin.rana@gmx.de
        send_resolved: false
        from: nitin.rana@gmx.de
        smarthost: smtp.eample.com:25
        require_tls: false
