apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'HAC-node-exporter'
        static_configs:
          - targets: ['acvml2600:9100', 'acvml2601:9100', 'acvml2602:9100', 'acvml2603:9100', 'acvml2604:9100', 'acvml2605:9100', 'lvmql264:9100']
      - job_name: 'lvmmetrics'
        static_configs:
          - targets: ['acvml2604.wdf.sap.corp:50000']
        metrics_path: '/LVMMetrics/'
        basic_auth:
          username: 'promuser'
          password: 'abcd1234'
      - job_name: 'nrllvmmetrics'
        static_configs:
          - targets: ['lvmql264.wdf.sap.corp:50000']
        metrics_path: '/LVMMetrics/'
        basic_auth:
          username: 'administrator'
          password: 'Linux4321'